version: "3.9"

services:
  bot:
    container_name: discordpollbot
    build: .
    restart: unless-stopped
    command: npm run dev
    environment:
      - NODE_ENV=production
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - CHANNEL_ID=${CHANNEL_ID}
    volumes:
      - .:/usr/src/app
      - ./firebase-key.json:/usr/src/app/firebase-key.json
    ports:
      - "3000:3000"
    working_dir: /usr/src/app
    tty: true
